// lib/services/notifications.ts

import { getClient } from '@/lib/supabase/client';

// สร้าง in-app notification
export async function createNotification(data: {
  userId: string;
  type: 'reminder' | 'announcement' | 'schedule_change' | 'payment' | 'makeup';
  title: string;
  body: string;
  imageUrl?: string;
  actionUrl?: string;
  data?: any;
}): Promise<string> {
  try {
    const supabase = getClient();
    const { data: notification, error } = await supabase
      .from('notifications')
      .insert({
        user_id: data.userId,
        user_type: 'admin', // Default to admin for now
        type: data.type,
        title: data.title,
        body: data.body,
        image_url: data.imageUrl || null,
        action_url: data.actionUrl || null,
        data: data.data || {},
        is_read: false
      })
      .select()
      .single();

    if (error) throw error;
    return notification.id;
  } catch (error) {
    console.error('Error creating notification:', error);
    throw error;
  }
}

// แจ้งเตือน Admin เมื่อมี auto-generated makeup
export async function notifyAdminNewMakeup(
  studentName: string,
  className: string,
  missedSessions: number,
  branchId?: string // เพิ่ม parameter
): Promise<void> {
  try {
    if (branchId) {
      // ส่งเฉพาะ admin ในสาขานั้น
      await notifyAdminsInBranch(branchId, {
        type: 'makeup',
        title: 'มี Makeup Class อัตโนมัติใหม่',
        body: `นักเรียน ${studentName} ในคลาส ${className} มีการขาดเรียน ${missedSessions} ครั้ง (สร้างอัตโนมัติจากการสมัครหลังคลาสเริ่ม)`,
        actionUrl: '/makeup',
        data: {
          studentName,
          className,
          missedSessions,
          autoGenerated: true,
          branchId
        }
      });
    } else {
      // ส่งให้ทุกคน (เหมือนเดิม)
      await createNotification({
        userId: 'admin',
        type: 'makeup',
        title: 'มี Makeup Class อัตโนมัติใหม่',
        body: `นักเรียน ${studentName} ในคลาส ${className} มีการขาดเรียน ${missedSessions} ครั้ง (สร้างอัตโนมัติจากการสมัครหลังคลาสเริ่ม)`,
        actionUrl: '/makeup',
        data: {
          studentName,
          className,
          missedSessions,
          autoGenerated: true
        }
      });
    }
    
    console.log(`[Notification] Created auto-generated makeup notification for ${studentName}`);
  } catch (error) {
    console.error('Error sending notification:', error);
  }
}

export async function notifyAdminsInBranch(
  branchId: string,
  notification: {
    type: 'reminder' | 'announcement' | 'schedule_change' | 'payment' | 'makeup';
    title: string;
    body: string;
    imageUrl?: string;
    actionUrl?: string;
    data?: any;
  }
): Promise<void> {
  try {
    // Get all admins for this branch
    const { getAdminUsers } = await import('./admin-users');
    const admins = await getAdminUsers(branchId);
    
    // Create notification for each admin
    const promises = admins.map(admin => 
      createNotification({
        userId: admin.uid,
        ...notification
      })
    );
    
    await Promise.all(promises);
    
    console.log(`[Notification] Sent to ${admins.length} admins in branch ${branchId}`);
  } catch (error) {
    console.error('Error sending branch notifications:', error);
  }
}

// ดึง notifications ที่ยังไม่ได้อ่าน
export async function getUnreadNotifications(userId: string): Promise<any[]> {
  try {
    const supabase = getClient();
    const { data, error } = await supabase
      .from('notifications')
      .select('*')
      .eq('user_id', userId)
      .eq('is_read', false)
      .order('sent_at', { ascending: false });

    if (error) throw error;

    return (data || []).map(notification => ({
      id: notification.id,
      userId: notification.user_id,
      userType: notification.user_type,
      type: notification.type,
      title: notification.title,
      body: notification.body,
      imageUrl: notification.image_url,
      actionUrl: notification.action_url,
      data: notification.data,
      sentAt: new Date(notification.sent_at),
      readAt: notification.read_at ? new Date(notification.read_at) : undefined,
      isRead: notification.is_read
    }));
  } catch (error) {
    console.error('Error getting unread notifications:', error);
    return [];
  }
}

// Mark notification as read
export async function markNotificationAsRead(
  userId: string,
  notificationId: string
): Promise<void> {
  try {
    const supabase = getClient();
    const { error } = await supabase
      .from('notifications')
      .update({
        is_read: true,
        read_at: new Date().toISOString()
      })
      .eq('id', notificationId)
      .eq('user_id', userId);

    if (error) throw error;
  } catch (error) {
    console.error('Error marking notification as read:', error);
  }
}