'use client';

import { useEffect, useState, useMemo } from 'react';
import { useQuery, useQueryClient } from '@tanstack/react-query';
import { MakeupClass } from '@/types/models';
import { getMakeupClasses, deleteMakeupClass, recordMakeupAttendance } from '@/lib/services/makeup';
import { getActiveBranches } from '@/lib/services/branches';
import { Card, CardContent } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { SearchInput } from '@/components/ui/search-input';
import { Badge } from '@/components/ui/badge';
import { Alert, AlertDescription } from '@/components/ui/alert';
import { cn } from '@/lib/utils';
import { Pagination, usePagination } from '@/components/ui/pagination';
import {
  Calendar,
  AlertCircle,
  CheckCircle,
  XCircle,
  Plus,
  Eye,
  CalendarCheck,
  MoreVertical,
  Trash2,
  Sparkles,
  Bot
} from 'lucide-react';
import { toast } from 'sonner';
import { formatDate, formatDateShort } from '@/lib/utils';
// Select removed — class filter merged into search
import {
  Table,
  TableBody,
  TableCell,
  TableHead,
  TableHeader,
  TableRow,
} from "@/components/ui/table";
import {
  DropdownMenu,
  DropdownMenuContent,
  DropdownMenuItem,
  DropdownMenuLabel,
  DropdownMenuSeparator,
  DropdownMenuTrigger,
} from "@/components/ui/dropdown-menu";
import {
  AlertDialog,
  AlertDialogAction,
  AlertDialogCancel,
  AlertDialogContent,
  AlertDialogDescription,
  AlertDialogFooter,
  AlertDialogHeader,
  AlertDialogTitle,
} from "@/components/ui/alert-dialog";
import { useRouter } from 'next/navigation';
import Link from 'next/link';
import { Textarea } from '@/components/ui/textarea';
import { Label } from '@/components/ui/label';
import { useMakeup } from '@/contexts/MakeupContext';
import { useBranch } from '@/contexts/BranchContext';
import { PermissionGuard } from '@/components/auth/permission-guard';
import { EmptyState } from '@/components/ui/empty-state';
import { SectionLoading } from '@/components/ui/loading';
import { useSupabaseAuth } from '@/hooks/useSupabaseAuth';
import ScheduleMakeupDialog from '@/components/makeup/schedule-makeup-dialog';
import CreateMakeupDialog from '@/components/makeup/create-makeup-dialog';

const statusColors = {
  'pending': 'bg-yellow-100 text-yellow-700',
  'scheduled': 'bg-blue-100 text-blue-700',
  'completed': 'bg-green-100 text-green-700',
  'cancelled': 'bg-red-100 text-red-700',
};

const statusLabels = {
  'pending': 'รอจัดตาราง',
  'scheduled': 'นัดแล้ว',
  'completed': 'เรียนแล้ว',
  'cancelled': 'ยกเลิก',
};

const statusIcons = {
  'pending': AlertCircle,
  'scheduled': CalendarCheck,
  'completed': CheckCircle,
  'cancelled': XCircle,
};

// Helper: detect if makeup is auto-generated from mid-term enrollment
// Detect auto-generated makeup from mid-term enrollment (by reason text)
function isAutoGeneratedMakeup(makeup: MakeupClass): boolean {
  return makeup.reason.includes('สมัครเรียนหลังจากคลาสเริ่มแล้ว');
}

// Cache key constants
const QUERY_KEYS = {
  makeupClasses: (branchId?: string | null) => ['makeupClasses', branchId],
  branches: ['branches', 'active'],
};

export default function MakeupPage() {
  const router = useRouter();
  const queryClient = useQueryClient();
  const { refreshMakeupCount } = useMakeup();
  const { selectedBranchId, isAllBranches } = useBranch();
  const { user } = useSupabaseAuth();

  // Filters
  const [searchTerm, setSearchTerm] = useState('');
  const [filterStatus, setFilterStatus] = useState<string>('all');
  const [filterType, setFilterType] = useState<string>('all');
  const [filterOverdue, setFilterOverdue] = useState(false);
  
  // Create dialog
  const [showCreateDialog, setShowCreateDialog] = useState(false);

  // Schedule dialog
  const [scheduleMakeup, setScheduleMakeup] = useState<MakeupClass | null>(null);
  const [showScheduleDialog, setShowScheduleDialog] = useState(false);

  // Attendance dialog
  const [attendanceMakeup, setAttendanceMakeup] = useState<MakeupClass | null>(null);
  const [showAttendanceDialog, setShowAttendanceDialog] = useState(false);
  const [markingAttendance, setMarkingAttendance] = useState(false);
  const [attendanceChoice, setAttendanceChoice] = useState<'present' | 'absent'>('present');

  // Delete dialog
  const [selectedMakeup, setSelectedMakeup] = useState<MakeupClass | null>(null);
  const [showDeleteDialog, setShowDeleteDialog] = useState(false);
  const [deleteReason, setDeleteReason] = useState('');
  const [deletingId, setDeletingId] = useState<string | null>(null);

  // Pagination
  const {
    currentPage,
    pageSize,
    handlePageChange,
    handlePageSizeChange,
    resetPagination,
    getPaginatedData,
    totalPages,
  } = usePagination(20);

  // Query: Makeup Classes
  const { data: makeupClasses = [], isLoading: loadingMakeup } = useQuery({
    queryKey: QUERY_KEYS.makeupClasses(selectedBranchId),
    queryFn: () => getMakeupClasses(selectedBranchId),
    staleTime: Infinity,
  });

  const { data: branches = [] } = useQuery({
    queryKey: QUERY_KEYS.branches,
    queryFn: getActiveBranches,
    staleTime: Infinity,
  });

  // Check if a scheduled makeup is overdue (past date but not recorded)
  const isMakeupOverdue = (makeup: MakeupClass): boolean => {
    if (makeup.status !== 'scheduled' || !makeup.makeupSchedule?.date) return false;
    const scheduleDate = new Date(makeup.makeupSchedule.date);
    const today = new Date();
    today.setHours(0, 0, 0, 0);
    return scheduleDate < today;
  };

  // Get unique classes from makeup data (for filter dropdown)
  // uniqueClasses removed — search covers class name filtering now

  // Filter makeup classes
  const filteredMakeupClasses = useMemo(() => {
    const filtered = makeupClasses.filter(makeup => {
      if (searchTerm) {
        const searchLower = searchTerm.toLowerCase();
        const matchesSearch =
          makeup.reason.toLowerCase().includes(searchLower) ||
          makeup.studentName.toLowerCase().includes(searchLower) ||
          makeup.studentNickname.toLowerCase().includes(searchLower) ||
          makeup.className.toLowerCase().includes(searchLower) ||
          makeup.classCode.toLowerCase().includes(searchLower) ||
          makeup.subjectName.toLowerCase().includes(searchLower);
        if (!matchesSearch) return false;
      }

      if (filterStatus !== 'all' && makeup.status !== filterStatus) return false;

      if (filterType !== 'all') {
        const isAuto = isAutoGeneratedMakeup(makeup);
        if (filterType === 'auto' && !isAuto) return false;
        if (filterType === 'manual' && isAuto) return false;
      }

      if (filterOverdue && !isMakeupOverdue(makeup)) return false;

      return true;
    });

    // Sort: scheduled → by makeup date ASC, others → by created_at DESC
    filtered.sort((a, b) => {
      if (filterStatus === 'scheduled' || (a.status === 'scheduled' && b.status === 'scheduled')) {
        const dateA = a.makeupSchedule?.date ? new Date(a.makeupSchedule.date).getTime() : Infinity;
        const dateB = b.makeupSchedule?.date ? new Date(b.makeupSchedule.date).getTime() : Infinity;
        return dateA - dateB; // ASC
      }
      return 0; // keep original order (already sorted by created_at DESC from API)
    });

    return filtered;
  }, [makeupClasses, searchTerm, filterStatus, filterType, filterOverdue]);

  // Get paginated data
  const paginatedMakeupClasses = getPaginatedData(filteredMakeupClasses);
  const calculatedTotalPages = totalPages(filteredMakeupClasses.length);

  // Reset pagination when filters change
  useMemo(() => {
    resetPagination();
  }, [searchTerm, filterStatus, filterType, filterOverdue, selectedBranchId, resetPagination]);

  // Calculate statistics
  const stats = useMemo(() => {
    const autoGeneratedMakeups = makeupClasses.filter(isAutoGeneratedMakeup);
    const pendingAutoGenerated = autoGeneratedMakeups.filter(m => m.status === 'pending');
    
    const manualMakeups = makeupClasses.filter(m => !isAutoGeneratedMakeup(m));
    const overdueMakeups = makeupClasses.filter(isMakeupOverdue);
    return {
      total: makeupClasses.length,
      pending: makeupClasses.filter(m => m.status === 'pending').length,
      scheduled: makeupClasses.filter(m => m.status === 'scheduled').length,
      completed: makeupClasses.filter(m => m.status === 'completed').length,
      cancelled: makeupClasses.filter(m => m.status === 'cancelled').length,
      autoGenerated: autoGeneratedMakeups.length,
      manual: manualMakeups.length,
      pendingAutoGenerated: pendingAutoGenerated.length,
      overdue: overdueMakeups.length,
    };
  }, [makeupClasses]);

  useEffect(() => {
    if (!loadingMakeup) {
      refreshMakeupCount();
    }
  }, [makeupClasses, loadingMakeup, refreshMakeupCount]);

  const handleViewDetail = (makeup: MakeupClass) => {
    router.push(`/makeup/${makeup.id}/edit`);
  };

  const handleSchedule = (makeup: MakeupClass) => {
    setScheduleMakeup(makeup);
    setShowScheduleDialog(true);
  };

  const handleMarkAttendance = (makeup: MakeupClass) => {
    setAttendanceMakeup(makeup);
    setAttendanceChoice('present');
    setShowAttendanceDialog(true);
  };

  const confirmMarkAttendance = async () => {
    if (!attendanceMakeup || !user?.uid) {
      toast.error('กรุณาเข้าสู่ระบบ');
      return;
    }
    setMarkingAttendance(true);
    try {
      await recordMakeupAttendance(attendanceMakeup.id, {
        status: attendanceChoice,
        checkedBy: user.uid,
        note: attendanceChoice === 'absent' ? 'ไม่มาเรียนชดเชย — ถือว่าเสร็จสมบูรณ์' : undefined,
      });
      toast.success(attendanceChoice === 'present' ? 'บันทึกเรียบร้อย — มาเรียนแล้ว' : 'บันทึกเรียบร้อย — ไม่มา ถือว่าเสร็จสมบูรณ์');
      setShowAttendanceDialog(false);
      queryClient.invalidateQueries({ queryKey: QUERY_KEYS.makeupClasses(selectedBranchId) });
      window.dispatchEvent(new CustomEvent('makeup-changed'));
    } catch (error: any) {
      console.error('Error marking attendance:', error);
      toast.error(error.message || 'เกิดข้อผิดพลาด');
    } finally {
      setMarkingAttendance(false);
    }
  };

  const handleQuickDelete = (makeup: MakeupClass) => {
    setSelectedMakeup(makeup);
    setDeleteReason('');
    setShowDeleteDialog(true);
  };

  const confirmDelete = async () => {
    if (!selectedMakeup || !deleteReason.trim()) {
      toast.error('กรุณาระบุเหตุผลในการลบ');
      return;
    }

    if (!user?.uid) {
      toast.error('กรุณาเข้าสู่ระบบ');
      return;
    }

    setDeletingId(selectedMakeup.id);
    try {
      await deleteMakeupClass(selectedMakeup.id, user.uid, deleteReason);
      toast.success('ลบ Makeup Class เรียบร้อยแล้ว');
      setShowDeleteDialog(false);

      queryClient.invalidateQueries({ queryKey: QUERY_KEYS.makeupClasses(selectedBranchId) });

      // Dispatch event to update sidebar badge
      window.dispatchEvent(new CustomEvent('makeup-changed'));
    } catch (error: any) {
      console.error('Error deleting makeup:', error);
      if (error.message === 'Cannot delete completed makeup class') {
        toast.error('ไม่สามารถลบ Makeup ที่เรียนเสร็จแล้วได้');
      } else {
        toast.error('ไม่สามารถลบได้');
      }
    } finally {
      setDeletingId(null);
    }
  };

  // Initial loading
  if (loadingMakeup) {
    return <SectionLoading />;
  }

  return (
    <div>
      <div className="flex justify-between items-center mb-8">
        <div>
          <h1 className="text-xl sm:text-3xl font-bold text-gray-900">
            การลา และชดเชย
            {/* {!isAllBranches && <span className="text-red-600 text-lg ml-2">(เฉพาะสาขาที่เลือก)</span>} */}
          </h1>
          <p className="text-gray-600 mt-1">การลา เรียนชดเชย Makeup Class</p>
        </div>
        <PermissionGuard requiredRole={['super_admin', 'branch_admin']}>
          <Button
            onClick={() => setShowCreateDialog(true)}
            className="bg-red-500 hover:bg-red-600"
          >
            <Plus className="h-4 w-4 mr-2" />
            สร้าง Makeup
          </Button>
        </PermissionGuard>
      </div>

      {/* Status Filter Tabs */}
      <div className="flex flex-wrap gap-3 mb-6">
        {[
          { value: 'all', label: 'ทั้งหมด', count: stats.total, labelColor: 'text-white', countColor: 'text-white', activeBg: 'bg-indigo-500', inactiveBg: 'bg-indigo-50', inactiveLabel: 'text-indigo-600', inactiveCount: 'text-indigo-700' },
          { value: 'pending', label: 'รอจัดตาราง', count: stats.pending, labelColor: 'text-white', countColor: 'text-white', activeBg: 'bg-yellow-400', inactiveBg: 'bg-yellow-50', inactiveLabel: 'text-yellow-600', inactiveCount: 'text-yellow-700' },
          { value: 'scheduled', label: 'นัดแล้ว', count: stats.scheduled, labelColor: 'text-white', countColor: 'text-white', activeBg: 'bg-blue-500', inactiveBg: 'bg-blue-50', inactiveLabel: 'text-blue-600', inactiveCount: 'text-blue-700' },
          { value: 'completed', label: 'เรียนแล้ว', count: stats.completed, labelColor: 'text-white', countColor: 'text-white', activeBg: 'bg-green-500', inactiveBg: 'bg-green-50', inactiveLabel: 'text-green-600', inactiveCount: 'text-green-700' },
          { value: 'cancelled', label: 'ยกเลิก', count: stats.cancelled, labelColor: 'text-white', countColor: 'text-white', activeBg: 'bg-gray-500', inactiveBg: 'bg-gray-50', inactiveLabel: 'text-gray-500', inactiveCount: 'text-gray-600' },
        ].map((tab) => {
          const isActive = filterStatus === tab.value;
          return (
            <button
              key={tab.value}
              onClick={() => setFilterStatus(tab.value)}
              className={cn(
                'flex flex-col items-center justify-center w-24 h-[72px] rounded-xl transition-all',
                isActive
                  ? `${tab.activeBg} shadow-md`
                  : `${tab.inactiveBg} hover:shadow-sm`
              )}
            >
              <span className={cn(
                'text-sm font-medium',
                isActive ? tab.labelColor : tab.inactiveLabel
              )}>
                {tab.label}
              </span>
              <span className={cn(
                'text-2xl font-bold mt-0.5',
                isActive ? tab.countColor : tab.inactiveCount
              )}>
                {tab.count}
              </span>
            </button>
          );
        })}
      </div>

      {/* Source Tabs */}
      <div className="flex gap-2 mb-4">
        {[
          { value: 'manual', label: 'ลา / ขาดเรียน / แจ้งผ่าน LINE', count: stats.manual },
          { value: 'auto', label: 'สมัครเรียนระหว่างคอร์ส', count: stats.autoGenerated },
        ].map((tab) => (
          <button
            key={tab.value}
            onClick={() => setFilterType(filterType === tab.value ? 'all' : tab.value)}
            className={cn(
              'px-4 py-2 rounded-full text-sm font-medium transition-all',
              filterType === tab.value
                ? 'bg-gray-900 text-white shadow-sm'
                : 'bg-gray-100 text-gray-600 hover:bg-gray-200'
            )}
          >
            {tab.label} <span className="ml-1 opacity-70">{tab.count}</span>
          </button>
        ))}
      </div>

      {/* Filters */}
      <div className="flex flex-col md:flex-row gap-4 mb-6">
        <SearchInput
          placeholder="ค้นหานักเรียน, คลาส, วิชา..."
          value={searchTerm}
          onChange={setSearchTerm}
          className="flex-1"
        />
        {stats.overdue > 0 && (
          <button
            onClick={() => setFilterOverdue(!filterOverdue)}
            className={cn(
              'flex items-center gap-2 px-4 py-2 rounded-lg text-sm font-medium border transition-all shrink-0',
              filterOverdue
                ? 'bg-red-600 text-white border-red-600'
                : 'bg-red-50 text-red-700 border-red-200 hover:bg-red-100'
            )}
          >
            <AlertCircle className="h-4 w-4" />
            เลยกำหนด {stats.overdue}
          </button>
        )}
      </div>

      {/* Mobile Card View */}
      <div className="md:hidden space-y-3">
        {filteredMakeupClasses.length === 0 ? (
          <Card>
            <CardContent className="p-0">
              <EmptyState
                icon={Calendar}
                title="ไม่พบข้อมูล Makeup Class"
                description={
                  searchTerm || filterType !== 'all' || filterOverdue
                    ? 'ลองปรับเงื่อนไขการค้นหา'
                    : 'ยังไม่มีการขอ Makeup Class'
                }
              />
            </CardContent>
          </Card>
        ) : (
          <>
            {paginatedMakeupClasses.map((makeup) => {
              const StatusIcon = statusIcons[makeup.status];
              const isAutoGenerated = isAutoGeneratedMakeup(makeup);
              const overdue = isMakeupOverdue(makeup);

              return (
                <Link key={makeup.id} href={`/makeup/${makeup.id}/edit`}>
                  <div className={cn(
                    'border rounded-xl p-4 space-y-2 transition-colors',
                    overdue ? 'bg-red-50 border-red-200' : isAutoGenerated ? 'bg-orange-50 border-orange-200' : 'bg-white border-gray-200',
                    'active:bg-gray-50'
                  )}>
                    {/* Top row: Student name + Status */}
                    <div className="flex items-start justify-between gap-2">
                      <div className="min-w-0 flex-1">
                        <p className="text-base font-medium text-gray-900 truncate">
                          {makeup.studentNickname
                            ? `${makeup.studentNickname} (${makeup.studentName.split(' ')[0]})`
                            : makeup.studentName}
                        </p>
                      </div>
                      <div className="flex items-center gap-1.5 shrink-0">
                        {overdue && (
                          <Badge className="bg-red-100 text-red-700 text-[10px] px-1.5 py-0">
                            เลยกำหนด
                          </Badge>
                        )}
                        {isAutoGenerated && (
                          <Badge variant="outline" className="text-[10px] px-1.5 py-0 border-orange-300 text-orange-600">
                            <Sparkles className="h-2.5 w-2.5 mr-0.5" />
                            Auto
                          </Badge>
                        )}
                        <Badge className={`${statusColors[makeup.status]} text-xs`}>
                          <StatusIcon className="h-3 w-3 mr-1" />
                          {statusLabels[makeup.status]}
                        </Badge>
                      </div>
                    </div>

                    {/* Class info */}
                    <p className="text-base text-gray-700">
                      {makeup.className}
                      <span className="text-gray-400 mx-1">·</span>
                      <span className="text-gray-500">{makeup.subjectName}</span>
                    </p>

                    {/* Session + Dates row */}
                    <div className="flex flex-wrap items-center gap-x-4 gap-y-1 text-base text-gray-500">
                      {makeup.originalSessionNumber && (
                        <span className="text-red-600 font-medium">
                          ครั้งที่ {makeup.originalSessionNumber}
                          {makeup.originalSessionDate && (
                            <span className="font-normal text-gray-500 ml-1">
                              ({formatDateShort(makeup.originalSessionDate)})
                            </span>
                          )}
                        </span>
                      )}
                      {makeup.makeupSchedule && (
                        <span className="text-blue-600">
                          นัด: {formatDate(makeup.makeupSchedule.date)} {makeup.makeupSchedule.startTime?.substring(0, 5)}-{makeup.makeupSchedule.endTime?.substring(0, 5)}
                        </span>
                      )}
                    </div>

                    {/* Reason */}
                    {makeup.reason && (
                      <div className="flex items-start gap-1">
                        {(isAutoGeneratedMakeup(makeup) || makeup.reason.includes('ลาผ่านระบบ')) && (
                          <Bot className="h-3.5 w-3.5 mt-0.5 shrink-0 text-gray-400" />
                        )}
                        <p className="text-sm text-gray-500 line-clamp-2">{makeup.reason}</p>
                      </div>
                    )}

                    {/* Branch (when viewing all branches) */}
                    {isAllBranches && (
                      <p className="text-base text-gray-400">{makeup.branchName}</p>
                    )}

                    {/* Primary action */}
                    {(makeup.status === 'pending' || makeup.status === 'scheduled') && (
                      <div className="pt-1">
                        {makeup.status === 'pending' && (
                          <Button
                            size="sm"
                            variant="outline"
                            className="text-blue-600 border-blue-300 hover:bg-blue-50 text-xs w-full"
                            onClick={(e) => { e.preventDefault(); handleSchedule(makeup); }}
                          >
                            <CalendarCheck className="h-3.5 w-3.5 mr-1" />
                            นัด Makeup
                          </Button>
                        )}
                        {makeup.status === 'scheduled' && (
                          <Button
                            size="sm"
                            className={cn(
                              'text-xs w-full',
                              overdue
                                ? 'bg-red-600 hover:bg-red-700 text-white'
                                : 'bg-green-600 hover:bg-green-700 text-white'
                            )}
                            onClick={(e) => { e.preventDefault(); handleMarkAttendance(makeup); }}
                          >
                            <CheckCircle className="h-3.5 w-3.5 mr-1" />
                            บันทึกเข้าเรียน
                          </Button>
                        )}
                      </div>
                    )}
                  </div>
                </Link>
              );
            })}

            <Pagination
              currentPage={currentPage}
              totalPages={calculatedTotalPages}
              pageSize={pageSize}
              totalItems={filteredMakeupClasses.length}
              onPageChange={handlePageChange}
              onPageSizeChange={handlePageSizeChange}
            />
          </>
        )}
      </div>

      {/* Table (Desktop) */}
      <Card className="hidden md:block">
        <CardContent className="p-0">
          {filteredMakeupClasses.length === 0 ? (
            <EmptyState
              icon={Calendar}
              title="ไม่พบข้อมูล Makeup Class"
              description={
                searchTerm || filterType !== 'all' || filterOverdue
                  ? 'ลองปรับเงื่อนไขการค้นหา'
                  : 'ยังไม่มีการขอ Makeup Class'
              }
            />
          ) : (
            <>
              <div className="overflow-x-auto">
                <Table>
                  <TableHeader>
                    <TableRow>
                      <TableHead className="min-w-[130px]">นักเรียน</TableHead>
                      <TableHead className="w-[110px]">ครั้งที่ขาด</TableHead>
                      <TableHead className="min-w-[130px]">คลาส</TableHead>
                      {isAllBranches && <TableHead className="w-[90px]">สาขา</TableHead>}
                      <TableHead className="max-w-[180px]">เหตุผล</TableHead>
                      <TableHead className="w-[110px]">วันที่นัด</TableHead>
                      <TableHead className="text-center w-[90px]">สถานะ</TableHead>
                      <TableHead className="w-[140px]"></TableHead>
                      <TableHead className="w-[40px]"></TableHead>
                    </TableRow>
                  </TableHeader>
                  <TableBody>
                    {paginatedMakeupClasses.map((makeup) => {
                      const StatusIcon = statusIcons[makeup.status];
                      const isAutoGenerated = isAutoGeneratedMakeup(makeup);

                      const overdue = isMakeupOverdue(makeup);

                      return (
                        <TableRow key={makeup.id} className={cn(
                          isAutoGenerated && 'bg-orange-50',
                          overdue && 'bg-red-50',
                        )}>
                          <TableCell className="align-top">
                            <div>
                              <p className="font-medium">
                                {makeup.studentNickname ? `${makeup.studentNickname} (${makeup.studentName.split(' ')[0]})` : makeup.studentName}
                                {isAutoGenerated && (
                                  <Badge variant="outline" className="ml-1.5 text-[10px] px-1 py-0 border-orange-300 text-orange-600">
                                    <Sparkles className="h-2.5 w-2.5 mr-0.5" />
                                    Auto
                                  </Badge>
                                )}
                              </p>
                              <p className="text-xs text-gray-500">{makeup.studentSchoolName || '-'}</p>
                            </div>
                          </TableCell>
                          <TableCell className="whitespace-nowrap align-top">
                            {makeup.originalSessionNumber ? (
                              <div>
                                <p className="font-medium text-red-600">
                                  ครั้งที่ {makeup.originalSessionNumber}
                                </p>
                                {makeup.originalSessionDate && (
                                  <p className="text-xs text-gray-500">
                                    {formatDateShort(makeup.originalSessionDate)}
                                  </p>
                                )}
                              </div>
                            ) : (
                              <span className="text-gray-400">-</span>
                            )}
                          </TableCell>
                          <TableCell className="align-top">
                            <div>
                              <p className="font-medium text-sm">{makeup.className}</p>
                              <p className="text-xs text-gray-500">{makeup.subjectName}</p>
                            </div>
                          </TableCell>
                          {isAllBranches && (
                            <TableCell className="align-top text-sm">
                              {makeup.branchName}
                            </TableCell>
                          )}
                          <TableCell className="align-top whitespace-normal">
                            <div className="max-w-[180px]">
                              <div className="flex items-start gap-1">
                                {(isAutoGeneratedMakeup(makeup) || makeup.reason.includes('ลาผ่านระบบ')) && (
                                  <span title="สร้างโดยระบบ"><Bot className="h-3.5 w-3.5 mt-0.5 shrink-0 text-gray-400" /></span>
                                )}
                                <p className="text-sm line-clamp-2" title={makeup.reason}>
                                  {makeup.reason}
                                </p>
                              </div>
                            </div>
                          </TableCell>
                          <TableCell className="whitespace-nowrap align-top">
                            {makeup.makeupSchedule ? (
                              <div>
                                <p className="text-sm">{formatDate(makeup.makeupSchedule.date)}</p>
                                <p className="text-xs text-gray-500">
                                  {makeup.makeupSchedule.startTime?.substring(0, 5)} - {makeup.makeupSchedule.endTime?.substring(0, 5)}
                                </p>
                              </div>
                            ) : (
                              <span className="text-gray-400">-</span>
                            )}
                          </TableCell>
                          <TableCell className="text-center align-top">
                            <div className="space-y-1">
                              <Badge className={`${statusColors[makeup.status]} text-xs`}>
                                <StatusIcon className="h-3 w-3 mr-1" />
                                {statusLabels[makeup.status]}
                              </Badge>
                              {overdue && (
                                <Badge className="bg-red-100 text-red-700 text-[10px] block">
                                  เลยกำหนด
                                </Badge>
                              )}
                            </div>
                          </TableCell>
                          {/* Primary action button */}
                          <TableCell className="align-top">
                            {makeup.status === 'pending' && (
                              <Button
                                size="sm"
                                variant="outline"
                                className="text-blue-600 border-blue-300 hover:bg-blue-50 text-xs h-8"
                                onClick={() => handleSchedule(makeup)}
                              >
                                <CalendarCheck className="h-3.5 w-3.5 mr-1" />
                                นัด Makeup
                              </Button>
                            )}
                            {makeup.status === 'scheduled' && (
                              <Button
                                size="sm"
                                className={cn(
                                  'text-xs h-8',
                                  overdue
                                    ? 'bg-red-600 hover:bg-red-700 text-white'
                                    : 'bg-green-600 hover:bg-green-700 text-white'
                                )}
                                onClick={() => handleMarkAttendance(makeup)}
                              >
                                <CheckCircle className="h-3.5 w-3.5 mr-1" />
                                บันทึกเข้าเรียน
                              </Button>
                            )}
                          </TableCell>
                          {/* More menu */}
                          <TableCell className="align-top">
                            <DropdownMenu>
                              <DropdownMenuTrigger asChild>
                                <Button variant="ghost" size="sm" className="h-8 w-8 p-0">
                                  <span className="sr-only">เปิดเมนู</span>
                                  <MoreVertical className="h-4 w-4" />
                                </Button>
                              </DropdownMenuTrigger>
                              <DropdownMenuContent align="end">
                                <DropdownMenuLabel>จัดการ</DropdownMenuLabel>
                                <DropdownMenuSeparator />

                                <DropdownMenuItem onClick={() => handleViewDetail(makeup)}>
                                  <Eye className="h-4 w-4 mr-2" />
                                  ดูรายละเอียด
                                </DropdownMenuItem>

                                <PermissionGuard requiredRole={['super_admin', 'branch_admin']}>
                                  {makeup.status === 'pending' && (
                                    <DropdownMenuItem
                                      onClick={() => handleSchedule(makeup)}
                                      className="text-blue-600"
                                    >
                                      <CalendarCheck className="h-4 w-4 mr-2" />
                                      นัด Makeup
                                    </DropdownMenuItem>
                                  )}

                                  {makeup.status === 'scheduled' && (
                                    <>
                                      <DropdownMenuItem
                                        onClick={() => handleSchedule(makeup)}
                                        className="text-blue-600"
                                      >
                                        <CalendarCheck className="h-4 w-4 mr-2" />
                                        เปลี่ยนวันนัด
                                      </DropdownMenuItem>
                                      <DropdownMenuItem
                                        onClick={() => handleMarkAttendance(makeup)}
                                        className="text-green-600"
                                      >
                                        <CheckCircle className="h-4 w-4 mr-2" />
                                        บันทึกการเข้าเรียน
                                      </DropdownMenuItem>
                                    </>
                                  )}

                                  {(makeup.status === 'pending' || makeup.status === 'scheduled') && (
                                    <>
                                      <DropdownMenuSeparator />
                                      <DropdownMenuItem
                                        onClick={() => handleQuickDelete(makeup)}
                                        className="text-red-600"
                                      >
                                        <Trash2 className="h-4 w-4 mr-2" />
                                        ลบ
                                      </DropdownMenuItem>
                                    </>
                                  )}
                                </PermissionGuard>
                              </DropdownMenuContent>
                            </DropdownMenu>
                          </TableCell>
                        </TableRow>
                      );
                    })}
                  </TableBody>
                </Table>
                  </div>

                  <Pagination
                    currentPage={currentPage}
                    totalPages={calculatedTotalPages}
                    pageSize={pageSize}
                    totalItems={filteredMakeupClasses.length}
                    onPageChange={handlePageChange}
                    onPageSizeChange={handlePageSizeChange}
                  />
                </>
              )}
          </CardContent>
        </Card>

      {/* Dialogs */}
      <AlertDialog open={showDeleteDialog} onOpenChange={setShowDeleteDialog}>
        <AlertDialogContent>
          <AlertDialogHeader>
            <AlertDialogTitle>ยืนยันการลบ Makeup Class</AlertDialogTitle>
            <AlertDialogDescription>
              คุณแน่ใจหรือไม่ที่จะลบ Makeup Class นี้? 
              การลบจะทำให้นักเรียนสามารถขอ Makeup ใหม่สำหรับวันนี้ได้
            </AlertDialogDescription>
          </AlertDialogHeader>
          {selectedMakeup && (
            <div className="my-4 space-y-3">
              <div className="bg-gray-50 rounded p-3 text-sm">
                <p><strong>นักเรียน:</strong> {selectedMakeup.studentName}</p>
                <p><strong>คลาส:</strong> {selectedMakeup.className}</p>
                <p><strong>สถานะ:</strong> {statusLabels[selectedMakeup.status]}</p>
                {isAutoGeneratedMakeup(selectedMakeup) && (
                  <p className="text-orange-600 mt-1">
                    <strong>หมายเหตุ:</strong> นี่คือ Makeup ที่สร้างอัตโนมัติ
                  </p>
                )}
              </div>
              <div>
                <Label htmlFor="delete-reason">เหตุผลในการลบ *</Label>
                <Textarea
                  id="delete-reason"
                  value={deleteReason}
                  onChange={(e) => setDeleteReason(e.target.value)}
                  placeholder="เช่น กรอกผิด, ผู้ปกครองขอยกเลิก..."
                  rows={3}
                  className="mt-2"
                />
              </div>
            </div>
          )}
          <AlertDialogFooter>
            <AlertDialogCancel>ไม่ลบ</AlertDialogCancel>
            <AlertDialogAction
              onClick={confirmDelete}
              disabled={!deleteReason.trim() || deletingId === selectedMakeup?.id}
              className="bg-red-500 hover:bg-red-600"
            >
              {deletingId === selectedMakeup?.id ? 'กำลังลบ...' : 'ยืนยันลบ'}
            </AlertDialogAction>
          </AlertDialogFooter>
        </AlertDialogContent>
      </AlertDialog>

      {/* Attendance Confirm Dialog */}
      <AlertDialog open={showAttendanceDialog} onOpenChange={setShowAttendanceDialog}>
        <AlertDialogContent>
          <AlertDialogHeader>
            <AlertDialogTitle>บันทึกเข้าเรียนชดเชย</AlertDialogTitle>
            <AlertDialogDescription>
              เลือกสถานะของนักเรียนสำหรับการเรียนชดเชยครั้งนี้
            </AlertDialogDescription>
          </AlertDialogHeader>
          {attendanceMakeup && (
            <div className="space-y-4">
              <div className="bg-gray-50 rounded-lg p-3 text-sm space-y-1">
                <p><strong>นักเรียน:</strong> {attendanceMakeup.studentNickname ? `${attendanceMakeup.studentNickname} (${attendanceMakeup.studentName.split(' ')[0]})` : attendanceMakeup.studentName}</p>
                <p><strong>คลาส:</strong> {attendanceMakeup.className}</p>
                {attendanceMakeup.makeupSchedule && (
                  <p><strong>วันที่นัด:</strong> {formatDate(attendanceMakeup.makeupSchedule.date)} {attendanceMakeup.makeupSchedule.startTime?.substring(0, 5)} - {attendanceMakeup.makeupSchedule.endTime?.substring(0, 5)}</p>
                )}
              </div>
              <div className="grid grid-cols-2 gap-3">
                <button
                  type="button"
                  onClick={() => setAttendanceChoice('present')}
                  className={cn(
                    'flex flex-col items-center gap-2 p-4 rounded-xl border-2 transition-all',
                    attendanceChoice === 'present'
                      ? 'border-green-500 bg-green-50 text-green-700'
                      : 'border-gray-200 text-gray-500 hover:border-gray-300'
                  )}
                >
                  <CheckCircle className="h-6 w-6" />
                  <span className="text-sm font-medium">มาเรียน</span>
                  <span className="text-xs text-gray-500">นักเรียนมาเรียนชดเชยแล้ว</span>
                </button>
                <button
                  type="button"
                  onClick={() => setAttendanceChoice('absent')}
                  className={cn(
                    'flex flex-col items-center gap-2 p-4 rounded-xl border-2 transition-all',
                    attendanceChoice === 'absent'
                      ? 'border-orange-500 bg-orange-50 text-orange-700'
                      : 'border-gray-200 text-gray-500 hover:border-gray-300'
                  )}
                >
                  <XCircle className="h-6 w-6" />
                  <span className="text-sm font-medium">ไม่มา</span>
                  <span className="text-xs text-gray-500">ถือว่าเสร็จสมบูรณ์</span>
                </button>
              </div>
            </div>
          )}
          <AlertDialogFooter>
            <AlertDialogCancel disabled={markingAttendance}>ยกเลิก</AlertDialogCancel>
            <AlertDialogAction
              onClick={confirmMarkAttendance}
              disabled={markingAttendance}
              className={attendanceChoice === 'present' ? 'bg-green-600 hover:bg-green-700' : 'bg-orange-600 hover:bg-orange-700'}
            >
              {markingAttendance ? 'กำลังบันทึก...' : 'ยืนยัน'}
            </AlertDialogAction>
          </AlertDialogFooter>
        </AlertDialogContent>
      </AlertDialog>

      {/* Create Makeup Dialog */}
      <CreateMakeupDialog
        open={showCreateDialog}
        onOpenChange={setShowCreateDialog}
        onSuccess={() => {
          queryClient.invalidateQueries({ queryKey: QUERY_KEYS.makeupClasses(selectedBranchId) });
          window.dispatchEvent(new CustomEvent('makeup-changed'));
        }}
      />

      {/* Schedule Makeup Dialog */}
      {scheduleMakeup && (
        <ScheduleMakeupDialog
          open={showScheduleDialog}
          onOpenChange={setShowScheduleDialog}
          makeupRequest={scheduleMakeup}
          onSuccess={() => {
            queryClient.invalidateQueries({ queryKey: QUERY_KEYS.makeupClasses(selectedBranchId) });
            window.dispatchEvent(new CustomEvent('makeup-changed'));
          }}
        />
      )}

    </div>
  );
}